// AJAX ACTION TYPES
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

// EVENT ACTION TYPES
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const UPDATE_EVENT_SUCCESS = "DELETE_EVENTS_SUCCESS";

// AUTH ACTION TYPES
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

// NOTIFICATION TYPES
export const NOTIFY_SUCCESS = "NOTIFY_SUCCESS";
export const NOTIFY_ERROR = "NOTIFY_ERROR";
export const NOTIFY_INFO = "NOTIFY_INFO";
export const NOTIFY_WARNING = "NOTIFY_WARNING";
export const NOTIFY_DEFAULT = "NOTIFY_DEFAULT";
